### ISSUE TITLE
VCPKG Doens't configure teplate Boost.Test project

### ISSUE THREAD

**Issue by okmechak** [microsoft/vs-boost-unit-test-adapter#119]
I have done step by step tutorial:
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-boost-test-for-cpp.md

And Boost.Test template doesn't appeared in VS 2017 and VS2019 too.

**Comment by spebl** [comment]
To clarify, for Boost.Test we do not provide a Project template, only an Item template. This can be added to an existing C++ project (or for a new project, you can start with the Empty C++ Project template) the same way you would add a new source file. If it's still not showing up there let me know and I can investigate. Thanks!
