### ISSUE TITLE
Error when a test settings file contains multiple filter patterns

### ISSUE THREAD

**Issue by ddinu** [Microsoft/vs-boost-unit-test-adapter#4]
An error occurs when using a custom test settings file with a filters section.

In the settings file, I have the config from below:

```
<BoostTest>
    <TestBatchStrategy>TestSuite</TestBatchStrategy>
    <ForceListContent>true</ForceListContent>
    <Filters>
        <Include>
            <Pattern>test_project1.exe$</Pattern>
            <Pattern>test_project2.exe$</Pattern>
        </Include>
        <Exclude>
            <Pattern>.dll$</Pattern>
        </Exclude>
    </Filters>
  </BoostTest>
```

After test discovery, I get the following message in the output console:

`An exception occurred while test discoverer 'BoostTestDiscoverer' was loading tests. Exception: An error occurred while initializing the settings provider named 'BoostTest'. Error: Invalid file defining property under BoostTest. The element 'Include' has invalid child element 'Pattern'.`

I'm using version 1.0.8.1 with Visual Studio Proffessional 2017 15.3.1.

This used to work with the pre-fork plugin on VS 2015.

**Comment by LukaszMendakiewicz** [comment]
Fixed by #6.
