### ISSUE TITLE
Allow for discovery of dynamically linked boost

### ISSUE THREAD

**Issue by LadislavSopko** [Microsoft/vs-boost-unit-test-adapter#70]
Hello.

Current version 1.0.8.2 don't support discovery tests from projects with boost dynamic link.
There is already done this in file : [BoostTestAdapter/Boost/Runner/BoostTestRunnerBase.cs](https://github.com/Microsoft/vs-boost-unit-test-adapter/blob/dev15/BoostTestAdapter/Boost/Runner/BoostTestRunnerBase.cs) line: 81
In branch: [[dev15](https://github.com/Microsoft/vs-boost-unit-test-adapter/tree/dev15)] in commit: [b183b04ecb4924048a1730931533a88ccf8030a0](https://github.com/Microsoft/vs-boost-unit-test-adapter/commit/b183b04ecb4924048a1730931533a88ccf8030a0#diff-91e0d9ce2e54ad719bbb52fe09dd92ec)

Could you please merge it in 1.0.8.2+
We can't use 1.0.8.2 due to boost dynamic link, 
We had to install manually created version from [[dev15](https://github.com/Microsoft/vs-boost-unit-test-adapter/tree/dev15)], Which is a pain cause 1.0.8.2 is now included in VS instal process.

Best regards
ladislav Sopko

**Comment by spebl** [comment]
Hi! Unfortunately we don't have any plans to backport fixes made to previous versions. Updating to the latest Update of Visual Studio 2017 should now have the latest version in the installer. If that doesn't work for you, the suggested work around is as you mentioned, building the adapter yourself and installing it.

**Comment by LadislavSopko** [comment]
Sorry to trouble you. 

Nice response after months of waiting. ...

Regards 
Ladislav
