### ISSUE TITLE
Assume exit code of 0 in case of process spawned by debug framework 

### ISSUE THREAD

**Issue by guwirth** [Microsoft/vs-boost-unit-test-adapter#77]
Align with latest test adapter for VS2015:

This is a common scenario when attempting to request the exit code of a process which is executed through the debugger. In such cases assume a successful exit scenario. Should this not be the case, the adapter will 'naturally' fail in other instances e.g. when attempting to read test reports.

See https://github.com/etas/vs-boost-unit-test-adapter/commit/2c4f130b7397a1399c666dfab51743ed59b99687 for an solution.

**Comment by LukaszMendakiewicz** [comment]
Fixed in #93.
